const MUTUAL_FUNDS = [
    { name: "ICICI Prudential Large Cap Fund-Growth", risk: "low", yearlyROI: 21.61, category: "Large Cap" },
    { name: "Nippon India Large Cap Fund-Growth", risk: "low", yearlyROI: 23.55, category: "Large Cap" },
    { name: "DSP Nifty 50 Equal Weight Index Fund Regular - Growth", risk: "low", yearlyROI: 20.07, category: "Index" },
    { name: "HDFC Large Cap Fund Regular-Growth", risk: "low", yearlyROI: 20.07, category: "Large Cap" },
    { name: "Axis Bluechip Fund", risk: "low", yearlyROI: 19.5, category: "Large Cap" },
    { name: "UTI Nifty Index Fund", risk: "low", yearlyROI: 18.8, category: "Index" },
    { name: "SBI ETF Nifty 50", risk: "low", yearlyROI: 18.5, category: "Index" },
    { name: "HDFC Liquid Fund", risk: "low", yearlyROI: 7.2, category: "Debt" },
    { name: "ICICI Prudential Liquid Fund", risk: "low", yearlyROI: 7.1, category: "Debt" },
    { name: "Nippon India Liquid Fund", risk: "low", yearlyROI: 7.0, category: "Debt" },
    { name: "Axis Midcap Fund", risk: "medium", yearlyROI: 18.0, category: "Mid Cap" },
    { name: "Kotak Emerging Equity Fund", risk: "medium", yearlyROI: 17.8, category: "Mid Cap" },
    { name: "DSP Midcap Fund", risk: "medium", yearlyROI: 17.5, category: "Mid Cap" },
    { name: "Edelweiss Mid Cap Fund", risk: "medium", yearlyROI: 17.2, category: "Mid Cap" },
    { name: "HDFC Mid-Cap Opportunities Fund", risk: "medium", yearlyROI: 17.0, category: "Mid Cap" },
    { name: "Mirae Asset Midcap Fund", risk: "medium", yearlyROI: 16.8, category: "Mid Cap" },
    { name: "Motilal Oswal Midcap Fund", risk: "medium", yearlyROI: 16.7, category: "Mid Cap" },
    { name: "SBI Magnum Midcap Fund", risk: "medium", yearlyROI: 16.5, category: "Mid Cap" },
    { name: "ICICI Prudential Midcap Fund", risk: "medium", yearlyROI: 16.3, category: "Mid Cap" },
    { name: "Franklin India Prima Fund", risk: "medium", yearlyROI: 16.0, category: "Mid Cap" },
    { name: "Quant Small Cap Fund", risk: "high", yearlyROI: 25.0, category: "Small Cap" },
    { name: "SBI Small Cap Fund", risk: "high", yearlyROI: 24.0, category: "Small Cap" },
    { name: "Nippon India Small Cap Fund", risk: "high", yearlyROI: 23.5, category: "Small Cap" },
    { name: "HDFC Small Cap Fund", risk: "high", yearlyROI: 23.0, category: "Small Cap" },
    { name: "Axis Small Cap Fund", risk: "high", yearlyROI: 22.8, category: "Small Cap" },
    { name: "Kotak Small Cap Fund", risk: "high", yearlyROI: 22.5, category: "Small Cap" },
    { name: "DSP Small Cap Fund", risk: "high", yearlyROI: 22.2, category: "Small Cap" },
    { name: "ICICI Prudential Smallcap Fund", risk: "high", yearlyROI: 22.0, category: "Small Cap" },
    { name: "Franklin India Smaller Companies Fund", risk: "high", yearlyROI: 21.8, category: "Small Cap" },
    { name: "Edelweiss Small Cap Fund", risk: "high", yearlyROI: 21.5, category: "Small Cap" },
    { name: "Mirae Asset Tax Saver Fund", risk: "medium", yearlyROI: 17.5, category: "ELSS" },
    { name: "Axis Long Term Equity Fund", risk: "medium", yearlyROI: 17.2, category: "ELSS" },
    { name: "ICICI Prudential Long Term Equity Fund", risk: "medium", yearlyROI: 17.0, category: "ELSS" },
    { name: "HDFC Tax Saver Fund", risk: "medium", yearlyROI: 16.8, category: "ELSS" },
    { name: "SBI Long Term Equity Fund", risk: "medium", yearlyROI: 16.5, category: "ELSS" },
    { name: "UTI Long Term Equity Fund", risk: "medium", yearlyROI: 16.3, category: "ELSS" },
    { name: "Franklin India Taxshield", risk: "medium", yearlyROI: 16.0, category: "ELSS" },
    { name: "Parag Parikh Flexi Cap Fund", risk: "medium", yearlyROI: 20.0, category: "Flexi Cap" },
    { name: "Motilal Oswal Flexi Cap Fund", risk: "medium", yearlyROI: 19.8, category: "Flexi Cap" },
    { name: "UTI Flexi Cap Fund", risk: "medium", yearlyROI: 19.5, category: "Flexi Cap" },
    { name: "HDFC Flexi Cap Fund", risk: "medium", yearlyROI: 19.2, category: "Flexi Cap" },
    { name: "ICICI Prudential Flexi Cap Fund", risk: "medium", yearlyROI: 19.0, category: "Flexi Cap" },
    { name: "SBI Flexi Cap Fund", risk: "medium", yearlyROI: 18.8, category: "Flexi Cap" },
    { name: "DSP Flexi Cap Fund", risk: "medium", yearlyROI: 18.5, category: "Flexi Cap" },
    { name: "Kotak Flexi Cap Fund", risk: "medium", yearlyROI: 18.2, category: "Flexi Cap" },
    { name: "Edelweiss Flexi Cap Fund", risk: "medium", yearlyROI: 18.0, category: "Flexi Cap" },
    { name: "Franklin India Flexi Cap Fund", risk: "medium", yearlyROI: 17.8, category: "Flexi Cap" },
    { name: "HDFC Corporate Bond Fund", risk: "low", yearlyROI: 8.0, category: "Debt" },
    { name: "ICICI Prudential Corporate Bond Fund", risk: "low", yearlyROI: 7.9, category: "Debt" },
    { name: "SBI Corporate Bond Fund", risk: "low", yearlyROI: 7.8, category: "Debt" },
    { name: "Kotak Corporate Bond Fund", risk: "low", yearlyROI: 7.7, category: "Debt" },
    { name: "Axis Corporate Bond Fund", risk: "low", yearlyROI: 7.6, category: "Debt" }
];

export default MUTUAL_FUNDS; 